# Generated by Django 2.2.10 on 2020-04-04 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200404_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-id',), 'verbose_name': 'Обзор', 'verbose_name_plural': 'Обзоры'},
        ),
    ]
